решение задачи 2
js-tasks-ru/js-20220613_aleksandr301 pull request #2
Opened 2022-06-19 12:36 UTC by panarin0290

2022-06-19 12:37 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-06-19 12:53 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-06-19 12:55 UTC, panarin0290 commented
Test Suites: 4 passed, 4 total
Tests:       13 passed, 13 total
Snapshots:   0 total
Time:        8.235s
Ran all test suites.

Все тесты проходят корректно, почему здесь появляется ошибка?

2022-06-19 13:12 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2022-06-20 14:46 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +        arrCopy.reverse()
Подумайте как исправить решение таким образом чтобы избавиться от `reverse` и сортировать данные сразу в верном порядке

2022-06-20 14:47 UTC, dosandk commented on 02-javascript-data-types/2-pick/index.js
> +    const object_ = {}
почему `object` заканчивается на знак нижнего подчеркивания?

2022-06-20 14:47 UTC, dosandk commented on 02-javascript-data-types/2-pick/index.js
> +        if (fields.indexOf(key) !== -1) object_[key] = obj[key]
сравните `indexOf` и `includes` методы, что здесь лучше подойдет?

2022-06-20 14:48 UTC, dosandk commented on 02-javascript-data-types/3-omit/index.js
> +    const object_ = {}
аналогичные вопросы как в `pick`

2022-06-20 14:48 UTC, dosandk requested changes
решение `sortStrings` следует поправить

2022-06-26 11:43 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2022-06-26 11:47 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2022-06-26 11:51 UTC, panarin0290 commented on 02-javascript-data-types/2-pick/index.js
> +        if (fields.indexOf(key) !== -1) object_[key] = obj[key]
includes - возвращает true при наличии искомого элемента в массиве

2022-06-26 17:49 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2022-06-27 07:54 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +        arrCopy.sort((value1, value2) => {
строки 10-12 и 15-17 дублируют друг-друга.
Подумайте как исправить

2022-06-27 07:55 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/1-create-getter/index.js
> +    const arr = path.split('.')
👍 good  лайк за замыкание

2022-06-27 07:55 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/2-invert-object/index.js
>  export function invertObj(obj) {
👍 good

2022-06-27 07:55 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/3-trim-symbols/index.js
>  export function trimSymbols(string, size) {
👍 good

2022-06-27 07:56 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/4-uniq/index.js
> +    return [...new Set(arr)]
👍 good 
альтернатива: `Array.from`. Помните в чем отличие?

2022-06-27 07:58 UTC, dosandk commented on 04-oop-basic-intro-to-dom/1-column-chart/index.js
> +        this.formatHeading = params.formatHeading || function (data){};
значением по умолчанию для `formatHeading` должна быть функция которая просто возвращает переданное ей значение:
```
// стрелка
data => data
// или
function (data) {
  return data;
}
```

2022-06-27 07:58 UTC, dosandk commented on 04-oop-basic-intro-to-dom/1-column-chart/index.js
> +        <div class="column-chart" style="--chart-height: 50">
50 нужно вынести в переменную или поле класса

2022-06-27 07:59 UTC, dosandk commented on 04-oop-basic-intro-to-dom/1-column-chart/index.js
> +    render(){
а где методы:
- `remove`
- `destroy`
- `update`
Их требуют тесты

2022-06-27 08:00 UTC, dosandk requested changes
Решение `ColumnChart` следует поправить. Смотрите комменты.
Также необходимо решить конфликты в PR

2022-06-29 20:06 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2022-06-30 06:32 UTC, dosandk commented on 04-oop-basic-intro-to-dom/1-column-chart/index.js
> +        let {link, data, label, value, formatHeading} = params || {}
тут `const`
лучше сделать эту деструкцию прямо в аргументах метода

2022-06-30 06:33 UTC, dosandk commented on 04-oop-basic-intro-to-dom/1-column-chart/index.js
> +        this.link = link || '#'
здесь не может быть значение `#` по умолчанию

2022-06-30 06:33 UTC, dosandk commented on 04-oop-basic-intro-to-dom/1-column-chart/index.js
> +        this.label = label || 'Main'
здесь не может быть `Main` значением по умолчанию

2022-06-30 06:33 UTC, dosandk commented on 04-oop-basic-intro-to-dom/1-column-chart/index.js
> +    destroy(){}
```
destroy(){
  this.remove()
}
```

2022-06-30 06:34 UTC, dosandk approved these changes
good 👍

2022-06-30 06:35 UTC, merged

2022-06-30 07:15 UTC, panarin0290 commented on 04-oop-basic-intro-to-dom/1-column-chart/index.js
> +        this.label = label || 'Main'
Здесь значения по умолчанию не должно быть? Потому что если нет данных используется заглушка в виде картинки?

2022-06-30 07:15 UTC, panarin0290 commented on 04-oop-basic-intro-to-dom/1-column-chart/index.js
> +        this.link = link || '#'
Здесь значения по умолчанию не должно быть? Потому что если нет данных используется заглушка в виде картинки?